<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KpiTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('add_kpis')->insert([
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => '90% pematuhan prosedur pelaksanaan hukuman dan persekitaran selamat',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 09:21:24',
                'updated_at' => '2024-11-17 09:21:24',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => '100% Permohonan Menaiktaraf 10 Institusi Kepada Sistem Artificial Inteligen (AI) Dalam Pengurusan SKEB',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 09:21:38',
                'updated_at' => '2024-11-17 09:21:38',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 90% banduan yang mengikuti PdP LINUS mengikut modul PROSHIP menguasai kemahiran 3M (Membaca, Menulis, Mengira) ',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:15',
                'updated_at' => '2024-11-17 11:28:15',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 100% banduan kemasukan baharu yang menjalani pemeriksaan perubatan semasa kemasukan',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 85% bilangan Perantis mengikuti latihan kemahiran dengan persijilan tahap pertengahan',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Melaksanakan 100% ujian tahap kepulihan Biofeedback bagi banduan radikal dan risiko tinggi',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => '100% banduan Jenayah Terancang dan ATIPSOM yang layak dipertimbangkan untuk menjalani pemulihan dalam komuniti',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Melaksanaan 3 Program Kolaborasi dengan agensi dan komuniti',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Pengajuran 100% Kursus/ Simposium/ Bengkel/ Seminar di Peringkat Antarabangsa Secara Kolabrasi.',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Melaksanakan 100% Program Latihan/ Kursus Yang Diluluskan Dalam Pelan Operasi Latihan (POL)',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 100% Kakitangan Menghadiri Program Latihan/ Kursus Setahun',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Menyediakan (3) kertas cadangan bagi bayaran elaun/ insentif untuk pegawai yang layak disediakan',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Menyediakan (4) kertas cadangan penstrukturan semula dan pengukuhan perjawatan Jabatan Penjara Malaysia',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 98% Prestasi  Perbelanjaan Belanja Mengurus',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan Prestasi Bayaran Bil dalam tempoh 7 hari',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => '(1) Permohonan penggantian penjara usang di bawah Rolling Plan Rancangan Malaysia setiap tahun',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 80% proses perolehan tender terbuka (bekalan/perkhidmatan) diselesaikan sehingga peringkat pengeluaran Surat Setuju Terima dalam tempoh enam (6) bulan dari tarikh tutup iklan.',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 95% Sistem Pengurusan Maklumat Beroperasi (Pusat Data)',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 25,000 dosir banduan yang layak dipertimbangkan bagi menjalani pemulihan dalam komuniti.',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Mewujudkan 3,000 peluang pekerjaan kepada ODP/OBB/PBL/ODS',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 250 Banduan Warga Asing menyertai Program Penempatan, Pekerjaan dan Pendapatan (3P)',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan (100) banduan warga asing dihantar pulang ke negara asal melalui program FAST',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Meningkatkan peratusan  (%) pencapaian rundingan pemindahan banduan warga asing melalui Triti',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Penganjuran sekurang-kurangnya 1 persidangan/seminar Koreksional peringkat Antarabangsa',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 100% pelaksanaan pengurusan penilaian KYKO terhadap banduan yang berada di Penjara Satelit dengan lebih efisyen dan sistematik',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Melaksanakan (4) Program dengan penglibatan Masyarakat ',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan pelajar tahfiz menghafaz sekurang-kurangnya 3 juzuk Al-Quran',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Penggantian 4% Kenderaan Yang Usang ',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan Sekurang-Kurangnya 80% Video Disiarkan Di Akaun Sosial Media Rasmi Jabatan Penjara Malaysia',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Mensasarkan 5% Peningkatan Pelayar/Pengikut Media Sosial Jabatan',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Memastikan 88 inisiatif PACP diselesaikan pada tahun 2024',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Melaksanakan audit sekurang-kurangnya 8 kali setahun',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
            [
                'teras_id' => 1,
                'sectors_id' => 1,
                'pernyataan_kpi' => 'Menyediakan 100% draf Akta Home Detention ',
                'jenis_sasaran' => json_encode(['bilangan']),
                'sasaran' => 100.00,
                'created_at' => '2024-11-17 11:28:28',
                'updated_at' => '2024-11-17 11:28:28',
                'status' => 'not achieved',
            ],
        ]);
    }
}
